{% set name = "raimitigations" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raimitigations-{{ version }}.tar.gz
  sha256: bc02a223ae2a2fb32ca18d518067317f8d62279e080cd74ce6f571866454c9a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - seaborn
    - scipy
    - scikit-learn
    - imbalanced-learn <=0.9.1
    - sdv ==0.18.0
    - mlxtend
    - researchpy
    - catboost
    - statsmodels
    - xgboost
    - raiutils

test:
  imports:
    - raimitigations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-toolbox-mitigations
  summary: Python library for implementing and exploring mitigations for Responsible AI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
